test:
  checkpoint_path: "checkpoints/vit-large-patch32-384_llava_train_all/train_all-epoch=00.ckpt"
  mapping_file: "class_mapping.json"
  test_csv: "data/test.csv"
  output_csv: "output/train_all_bestckp.csv" # <-- NEW: Where to save the results

model:
  id: "google/vit-large-patch32-384"
  projector_type: "llava"
  num_classes: 200

experiment:
  situation: "train_all"

data:
  batch_size: 64
  num_workers: 4

trainer:
  precision: "16-mixed"
  learning_rate: 0.0001